// AUTO-GENERATED BY BACKEND ETL PIPELINE
// Source: https://bugzilla.mozilla.org/rest/config/component_teams/{team}
// Component names mirror firefox_table.component in Supabase.

export const mozillaTaxonomy = {
  "DevTools": {
    "Core Tools": [
      "General",
      "Debugger",
      "Console",
      "Inspector",
      "Style Editor",
      "Source Editor",
      "Responsive Design Mode",
      "Netmonitor"
    ],
    "Panel & Views": [
      "Framework",
      "Object Inspector",
      "Storage Inspector",
      "JSON Viewer",
      "about:debugging",
      "Shared Components",
      "DOM",
      "Application Panel",
      "Documentation"
    ],
    "Inspector Sub-tools": [
      "Inspector: Rules",
      "Inspector: Animations",
      "Inspector: Changes",
      "Inspector: Layout",
      "Inspector: Compatibility"
    ],
    "Runtime & Source": [
      "View Source"
    ],
    "Other": [
      "MCP"
    ]
  },
  "Layout": {
    "Box Model & Flow": [
      "Layout",
      "Layout: Positioned",
      "Layout: Block and Inline",
      "Layout: Floats",
      "Layout: Scrolling and Overflow",
      "Layout: Columns",
      "Layout: Ruby"
    ],
    "Flexbox & Grid": [
      "Layout: Flexbox",
      "Layout: Generated Content, Lists, and Counters",
      "Layout: Grid"
    ],
    "CSS & Rendering": [
      "CSS Parsing and Computation",
      "DOM: CSS Object Model",
      "Panning and Zooming",
      "DOM: Animation",
      "CSS Transitions and Animations"
    ],
    "Media & Embedded": [
      "Layout: Tables",
      "Layout: Form Controls",
      "MathML",
      "SVG",
      "Layout: Images, Video, and HTML Frames",
      "Layout: Text and Fonts"
    ],
    "Print": [
      "Printing: Output",
      "Print Preview",
      "Printing: Setup"
    ]
  },
  "Networking": {
    "Protocols": [
      "Networking"
    ],
    "Cache & Storage": [
      "Networking: Cache"
    ],
    "Other": [
      "Networking: Cookies",
      "Networking: HTTP",
      "Networking: File",
      "Networking: JAR",
      "Networking: WebSockets",
      "Networking: DNS",
      "DOM: Networking",
      "Networking: Proxy",
      "Networking: FTP",
      "Networking: Domain Lists",
      "TRR Application"
    ]
  },
  "Firefox": {},
  "Core": {}
};

export const teamDescriptions = {
  "DevTools": "Browser developer tools: debugger, console, inspector, network monitor, and profiling panels.",
  "Layout": "The rendering engine that parses CSS/HTML and computes page geometry \u2014 flexbox, grid, SVG, and print.",
  "Networking": "All network I/O: HTTP, DNS, WebSockets, TLS certificates, caching, and cookies.",
  "Firefox": "The Firefox browser UI layer \u2014 tabs, address bar, bookmarks, sync, accessibility, and updates.",
  "Core": "The Gecko browser engine core: SpiderMonkey JS engine, DOM, graphics, IPC, and platform services."
};
